[window]
decorations = "None"
opacity = 0.95
blur = true
startup_mode = "Maximized"

[scrolling]
history = 10000
multiplier = 3

[font]
size = 16

[font.normal]
family = "JetbrainsMono NFM"
style = "Bold"

[env]
term = "xterm-256color"
